Updated xtk-utils/build.py to enforce strict code checking.
It came up with the following errors which should be easy fixable:

--

/Users/daniel/projectX/sampleApp/sampleApp.js:9: ERROR - variable
console is undefined
  console.log('Starting sampleApp.init..');
  ^

/Users/daniel/projectX/xtk/core/base.js:49: ERROR - variable attributes
is undefined
  attributes = Object.keys(this);
  ^

/Users/daniel/projectX/xtk/core/base.js:50: ERROR - variable
attributesStringList is undefined
  attributesStringList = '';
  ^

/Users/daniel/projectX/xtk/core/base.js:51: ERROR - variable className
is undefined
  className = '<unknown>';
  ^

/Users/daniel/projectX/xtk/core/base.js:56: ERROR - variable aName is
undefined
    aName = 'this.' + attributes[a];
    ^

/Users/daniel/projectX/xtk/core/base.js:57: ERROR - variable aValue is
undefined
    aValue = eval(aName);
    ^

/Users/daniel/projectX/xtk/core/base.js:69: ERROR - variable output is
undefined
  output = '== X.' + className + ' ==\n';
  ^

/Users/daniel/projectX/xtk/visualization/renderer.js:204: ERROR -
variable body is undefined
    body = document.body;
    ^

/Users/daniel/projectX/xtk/visualization/renderer.js:249: ERROR -
variable container is undefined
  container = goog.dom.getElement(containerId);
  ^

/Users/daniel/projectX/xtk/visualization/renderer.js:275: ERROR -
variable canvas is undefined
  canvas = goog.dom.createDom('canvas');
  ^

/Users/daniel/projectX/xtk/visualization/renderer.js:290: ERROR -
variable gl is undefined
    gl = canvas.getContext('experimental-webgl');
    ^

11 error(s), 0 warning(s)

--

Just the var in front is missing. I think this setting is good to
enforce nice coding.